services:
  nginx:
    image: nginx:1.26.1 #traffic_router:1.0.1
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Main NGINX configuration
      - ./nginx/conf.d:/etc/nginx/conf.d:ro          # Include configuration files
      - ./nginx/ip_lists:/etc/nginx/ip_lists:ro          # Include configuration files
    ports:
      - "80:80"
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge